# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DevStache
email: ma.craig006@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's add unnecessary stuff to the web together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jolly-dove.cloudvent.net" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mattacraig

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass: 
  sass_dir: _sass
  style: compressed
collections:
  category:
    output: true

